name: flutter_project_structure
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  dio: ^4.0.6
  equatable: ^2.0.5
  form_builder_validators: ^8.4.0
  flutter_form_builder: ^7.7.0
  flutter_dotenv: ^5.0.2
  flutter_easyloading: ^3.0.5
  get_it: ^7.2.0
  go_router: ^6.0.3
  provider: ^6.0.5
  retrofit: ^3.3.1
  timezone: ^0.9.1

  basic_flutter_theme:
    path: ../basic_flutter_theme

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  flutter_lints: ^2.0.1
  json_serializable: ^6.6.0
  retrofit_generator: ^4.2.0

flutter:
  uses-material-design: true

  assets:
    - .env

flutter_intl:
  enabled: true
  arb_dir: lib/src/core/l10n
  output_dir: lib/src/core/l10n/generated